// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://subpjcxuualasqtvzmbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1YnBqY3h1dWFsYXNxdHZ6bWJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NzE1MjEsImV4cCI6MjA2MDE0NzUyMX0.pul5PUIRfMjFc1QwgAS2XxzPWoM4TUvq46JEg-Smv_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);